export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const NOTIFICATION_ROUTE = '/notification'
export const MAP_ROUTE = '/'